pipeline: Relative Camera Pose Estimation pipeline
model_mode: accel 
data_params:
  work_dir: D:/Imperial/FYP/new/RelPoseNet
  img_dir: D:/Imperial/FYP/captured_data/airsim_drone_mode/relative_pose/building_relative_v2
  train_pairs_fname: ${data_params.img_dir}/train.txt
  val_pairs_fname: ${data_params.img_dir}/val.txt
model_params:
  backbone_net: resnet34
  resume_snapshot:  D:/Imperial/FYP/new/RelPoseNet/output/snapshots/accel/snapshot000004.pth
train_params:
  bs: 10
  lr: 1e-3
  alpha: 1
  pose_weight: 1
  imu_weight: 1
  n_workers: 0
  n_train_iters: 125000 # 42k is the size of our training dataset 'db_all_med_hard_train.txt'
  epoch: 10
  scheduler:
    lrate_decay_steps: 15000
    lrate_decay_factor: 0.5
output_params:
  out_dir: D:/Imperial/FYP/new/RelPoseNet/output
  logger_dir: ${output_params.out_dir}/tboard/${model_mode}
  snapshot_dir: ${output_params.out_dir}/snapshots/${model_mode}
  validate_interval: 2
  log_scalar_interval: 1
seed: 1984
hydra:
  run:
    dir: ${output_params.out_dir}
